In [2]:
import pandas as pd
import numpy as np

In [9]:
metrics_tcn = {
    'MAE': 10728.487788896975,
    'MSE': 194664455.61080828,
    'RMSE': np.float64(13952.220454494269),
    'MAPE (%)': np.float64(3.7897770194606344),
    'R2 Score': 0.9605575885977304,
    'model': 'TCN'
}

# Данные для ARIMA
metrics_arima = {
    'MAE': 5924.277551587905,
    'MSE': 84978861.0423676,
    'RMSE': np.float64(9218.39796506788),
    'MAPE (%)': np.float64(1.9782612735241254),
    'R2 Score': 0.9826465658931529,
    'model': 'ARIMA'
}
metrics_mlp = {
    'MAE': 52126.22014164492,
    'MSE': 4883206090.628575,
    'RMSE': np.float64(69879.94054539954),
    'MAPE (%)': np.float64(18.159802831075446),
    'R2 Score': 0.0028061792728848456,
    'model': 'MLP'
}

metrics_rf = {
    'MAE': 32082.982914429587,
    'MSE': 1869019664.5204241,
    'RMSE': np.float64(43232.160072339946),
    'MAPE (%)': np.float64(10.548468727945252),
    'R2 Score': 0.6017202598088718,
    'model': 'Random Forest'
}

metrics_gb = {
    'MAE': 17589.14682746556,
    'MSE': 388551534.26713866,
    'RMSE': np.float64(19711.710587037815),
    'MAPE (%)': np.float64(6.152153986637473),
    'R2 Score': 0.9206543443356174,
    'model': 'Gradient Boosting'
}

metrics_prophet = {
    'MAE': 2.000862e+04,
    'MSE': 5.681745e+08,
    'RMSE': 2.310886e+04,
    'MAPE (%)': 7.629103e+02,
    'R2 Score': 9.072388e-01,
    'model': 'Prophet'
}

metrics_lstm = {
    'MAE': 15462.923722287383,
    'MSE': 655558899.0042388,
    'RMSE': np.float64(25603.88445147023),
    'MAPE (%)': np.float64(4.925245306162742),
    'R2 Score': 0.8661290817800503,
    'model': 'LSTM'
}
metrics_gru = {
    'MAE': 13168.271960108292,
    'MSE': 272259152.1713873,
    'RMSE': np.float64(16500.27733619612),
    'MAPE (%)': np.float64(4.614977454292515),
    'R2 Score': 0.9448355507209466,
    'model': 'GRU'
}
# Преобразуем в DataFrame
df_metrics = pd.DataFrame([metrics_tcn,metrics_arima,metrics_mlp, metrics_rf, metrics_gb, metrics_prophet, metrics_lstm, metrics_gru])

print(df_metrics)

            MAE           MSE          RMSE    MAPE (%)  R2 Score  \
0  10728.487789  1.946645e+08  13952.220454    3.789777  0.960558
1   5924.277552  8.497886e+07   9218.397965    1.978261  0.982647
2  52126.220142  4.883206e+09  69879.940545   18.159803  0.002806
3  32082.982914  1.869020e+09  43232.160072   10.548469  0.601720
4  17589.146827  3.885515e+08  19711.710587    6.152154  0.920654
5  20008.620000  5.681745e+08  23108.860000  762.910300  0.907239
6  15462.923722  6.555589e+08  25603.884451    4.925245  0.866129
7  13168.271960  2.722592e+08  16500.277336    4.614977  0.944836

               model
0                TCN
1              ARIMA
2                MLP
3      Random Forest
4  Gradient Boosting
5            Prophet
6               LSTM
7                GRU

In [14]:
df_sorted

,MAE,MSE,RMSE,MAPE (%),R2 Score,model
0,5924.277552,8.497886e+07,9218.397965,1.978261,0.982647,ARIMA
1,10728.487789,1.946645e+08,13952.220454,3.789777,0.960558,TCN
2,13168.271960,2.722592e+08,16500.277336,4.614977,0.944836,GRU
3,15462.923722,6.555589e+08,25603.884451,4.925245,0.866129,LSTM
4,17589.146827,3.885515e+08,19711.710587,6.152154,0.920654,Gradient Boosting
5,20008.620000,5.681745e+08,23108.860000,762.910300,0.907239,Prophet
6,32082.982914,1.869020e+09,43232.160072,10.548469,0.601720,Random Forest
7,52126.220142,4.883206e+09,69879.940545,18.159803,0.002806,MLP

In [11]:
df_sorted = df_metrics.sort_values(by='MAE', ascending=True).reset_index(drop=True)

print(df_sorted)

            MAE           MSE          RMSE    MAPE (%)  R2 Score  \
0   5924.277552  8.497886e+07   9218.397965    1.978261  0.982647
1  10728.487789  1.946645e+08  13952.220454    3.789777  0.960558
2  13168.271960  2.722592e+08  16500.277336    4.614977  0.944836
3  15462.923722  6.555589e+08  25603.884451    4.925245  0.866129
4  17589.146827  3.885515e+08  19711.710587    6.152154  0.920654
5  20008.620000  5.681745e+08  23108.860000  762.910300  0.907239
6  32082.982914  1.869020e+09  43232.160072   10.548469  0.601720
7  52126.220142  4.883206e+09  69879.940545   18.159803  0.002806

               model
0              ARIMA
1                TCN
2                GRU
3               LSTM
4  Gradient Boosting
5            Prophet
6      Random Forest
7                MLP

In [13]:
print(df_sorted.iloc[5])

MAE            20008.62
MSE         568174500.0
RMSE           23108.86
MAPE (%)       762.9103
R2 Score       0.907239
model           Prophet
Name: 5, dtype: object